### ISSUE TITLE
Attempted to load class \"LdapClient\"

### ISSUE THREAD

**Issue by carukc** [Monogramm/MauticLdapAuthBundle#16]
**Describe the bug**
Hello and Thank you for providing this useful plugin.

I have been trying to get it on Mautic 3.2.5 with the version 3 branch of your plugin, but am seeing this error:

` [2021-02-03` 03:15:47] mautic.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "LdapClient" from namespace "Symfony\Component\Ldap". Did you forget a "use" statement for another namespace?" at /var/www/html/plugins/MauticLdapAuthBundle/Integration/LdapAuthIntegration.php line 117 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"LdapClient\" from namespace \"Symfony\\Component\\Ldap\".\nDid you forget a \"use\" statement for another namespace? at /var/www/html/plugins/MauticLdapAuthBundle/Integration/LdapAuthIntegration.php:117)"} []

**To Reproduce**

I think that this might be happening because Symphony/ldap is not installed correctly.

The README file says:

Install symfony/ldap requirements with composer: composer require symfony/ldap:~3.4.0

if I run the 'composer require symfony/ldap:~3.4.0' command in the /var/www/html folder it seems to remove every other component and kills Mautic.

If I run this command in the /var/www/html/plugins folder it seems to run and mautic continues to work, and I can see the plugin control panel and I can configure the LDAP settings BUT, when I try to login using an LDAP user I get the noted error

If it's important, I am attempting to login to our AD drivectory server using user@mydomain.com

**Docker (please complete the following information):**

-   I am using my own Dockerfile and docker-compose file.  The image is based on alpine and In my Dockerfile I have installed the dependencies required to successfully install the php ldap module (ldb-dev libldap openldap-dev libldap) using:
  docker-php-ext-install ldap 

**Additional context**

Do you think that this is an issue with symfony/ldap?

Where should I be installing symfony/ldap?

Could there be an issue in Mautic 3.2.5 that removes every other component when I try to install symfony/ldap?

Thanks for the help!

**Comment by gramakri** [comment]
@carukc You need a fix like https://github.com/Monogramm/MauticLdapAuthBundle/pull/18
