### ISSUE TITLE
Plugin autoactivation

### ISSUE THREAD

**Issue by nebulade** [Monogramm/MauticLdapAuthBundle#8]
Hi there,

I am packaging Mautic for Cloudron at the moment and found this great LDAP plugin. It works like a charm with the Cloudron built-in LDAP server. I am not sure if this is related to this plugin in particular or a mautic issue as such, but is there a way to activate this plugin from the commandline instead of through the mautic admin panel? 

Best,
Johannes

**Comment by madmath03** [comment]
Hi,

Glad to see that you like this plugin and it works great for you 😉 

As you guessed, this is not related to this plugin but rather to Mautic itself, so I will close this issue but give you a few hints to help you.

Mautic is based on Symfony and there are a few command line available: just open a terminal and execute `php /path/to/mautic/app/console` and it should display you the list of available commands.

We've also looked into this so I can share you a few commands that might do what you want : 
```shell
# Reload plugins available
php /path/to/mautic/app/console mautic:plugins:reload

# Install LDAP plugin
php /path/to/mautic/app/console mautic:plugins:install monogramm/mautic-ldapauth-bundle

# Copy LDAP config from existing source
cp .config/local.php /path/to/mautic/config/local.php
```

But I warn you : **the code above  is not tested** !
We wanted to automatize Mautic installation and install plugins automatically but it's not currently possible to install Mautic through command line... so kind of stopped working on it for now.

If you're interested though, we have an open PR for Mautic automatic install : https://github.com/mautic/mautic/pull/7395
Feel free to help test it if you're interested.

Also, I do not know if this can be compatible with Cloudron,  but we have a docker image that can set the LDAP properties through environment variables : https://github.com/Monogramm/docker-mautic

Hope this well help.

**Comment by nebulade** [comment]
Thanks for the reply, not sure if this is the correct way to discuss ;-)
Our package currently has the ldap plugin installed just fine and the LDAP settings are also dynamically injected into the local.php. Now if an admin logs into the app, he can activate the plugin in the mautic plugin settings, which result in a db record change, which I am trying to automate at https://git.cloudron.io/cloudron/mautic-app/blob/master/start.sh#L119
Unfortunately that db table itself only gets populated for a start once the first browser request hits mautic. So I guess this is just some quirk in symfony to work around?

**Comment by madmath03** [comment]
Yep, maybe there is a way to work with Symfony or Mautic command lines to force this database to be populated... but I would not bet it.

Mautic has a slack channel : https://www.mautic.org/slack/
Maybe you will find some help there.

You can contact by email if you want to further discuss this ;-)

**Comment by nebulade** [comment]
So far I wasn't able to figure out any way through symfony but to close this here, for reference for other users with this problem, we use this flow now as a crude workaround https://git.cloudron.io/cloudron/mautic-app/blob/master/start.sh#L5
