### ISSUE TITLE
ErrorHandler after composer require symfony/ldap:~2.8

### ISSUE THREAD

**Issue by phucvinh52** [Monogramm/MauticLdapAuthBundle#9]
Hi team,
I install via zip file and after run command `composer require symfony/ldap:~2.8` i get error in browser
```
Fatal error: Uncaught Error: Class 'Mautic\CoreBundle\ErrorHandler\ErrorHandler' not found in /var/www/html/index.php:29 
Stack trace: #0 {main} thrown in /var/www/html/index.php on line 29
```
Please help me resolve this issue. i try to install via `composer require monogramm/mautic-ldap-auth-bundle` but same problem.
Thanks

**Comment by madmath03** [comment]
Hello @phucvinh52 ,

This error does not seem to be related to this plugin but rather to your Mautic install. I suggest you create a ticket at https://github.com/mautic/mautic.

Also, our Docker image https://github.com/Monogramm/docker-mautic includes this plugin in the docker-compose use by Travis-CI, and the CI executes without encountering the error you mentioned here.
If you want an easy way to setup your Mantic environment, I suggest you to use the docker container.
